#!/bin/bash

source fixerio_funcs.sh

usage() {
  echo "Usage: $0 [-d yyyy-mm-dd] [-b currency] [-s symbols] [-f prettify-colorful|prettify|no]" 1>&2
  exit 1
}

base="EUR"
symbols=""
color="no"
date=""
while getopts "d:b:s:f:" o; do
    case "${o}" in
        d)
          date=${OPTARG}
          ;;
        b)
          base=${OPTARG}
          ;;
        s)
          symbols=${OPTARG}
          ;;
        f)
          color=${OPTARG}
          [[ "$color" = "prettify-colorful" || "$color" = "prettify" || "$color" = "no" ]] || usage
          ;;
        *)
          usage
          ;;
    esac
done
shift $((OPTIND-1))

if [[ "$date" = "" ]] ; then
  json=$(latest "$base" "$symbols")
else
  json=$(historical "$date" "$base" "$symbols")
fi

if [[ "$color" = "prettify-colorful" ]] ; then
  echo $json | jq .
elif [[ "$color" = "prettify" ]] ; then
  echo $json | jq -M .
else
  echo $json
fi
