#!/bin/bash

# style guide: https://google.github.io/styleguide/shell.xml

function get_url {
  local url="${1}"

  if [ -z ${res+x} ]; then
    res=$(curl -s $url)
  fi

  echo $res
}

function get_uri {
  local res=$(get_url http://api.fixer.io/$1)
  echo $res
}

function latest {
  local base="EUR"
  if [ ! -z ${1+x} ]; then
    base=$1
  fi
  local content=$(get_uri latest?base=$base)
  echo $content
}

#res="sas"
json=$(latest)
echo $json #| jq .
